name: Build iOS Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project TestRnM.xcodeproj

      - name: Build project
        run: |
          xcodebuild clean build \
            -project TestRnM.xcodeproj \
            -scheme TestRnM \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max' \
            CODE_SIGNING_ALLOWED=NO

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat
        run: swiftformat . --lint --strict

      - name: Notify Telegram
        run: |
          STATUS="✅ Build succeeded"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="❌ Build failed"
          fi
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="${STATUS} for TestRnM on GitHub Actions"
